/**
 * LSL Event Maps — Shared data used by both the transpiler and editor.
 *
 * Extracted from codegen.ts and parser.ts so the editor's hover/completion
 * providers can access event names and mappings without duplicating data.
 */

/** All known LSL event names */
export const LSL_EVENTS = new Set([
  "state_entry",
  "state_exit",
  "touch_start",
  "touch",
  "touch_end",
  "timer",
  "listen",
  "link_message",
  "collision_start",
  "collision",
  "collision_end",
  "sensor",
  "no_sensor",
  "on_rez",
  "changed",
  "run_time_permissions",
  "money",
  "attach",
  "control",
  "dataserver",
  "http_response",
  "http_request",
  "at_target",
  "not_at_target",
  "at_rot_target",
  "not_at_rot_target",
  "moving_start",
  "moving_end",
  "land_collision_start",
  "land_collision",
  "land_collision_end",
  "email",
  "remote_data",
  "object_rez",
  "experience_permissions",
  "experience_permissions_denied",
  "path_update",
  "transaction_result",
]);

/** Maps LSL event names to poqpoq TypeScript handler names */
export const EVENT_NAME_MAP: Record<string, string> = {
  state_entry: "onStateEntry",
  state_exit: "onStateExit",
  touch_start: "onTouchStart",
  touch: "onTouch",
  touch_end: "onTouchEnd",
  collision_start: "onCollisionStart",
  collision: "onCollision",
  collision_end: "onCollisionEnd",
  land_collision_start: "onLandCollisionStart",
  listen: "onListen",
  timer: "onTimer",
  sensor: "onSensor",
  no_sensor: "onNoSensor",
  on_rez: "onRez",
  changed: "onChanged",
  attach: "onAttach",
  money: "onMoney",
  control: "onControl",
  run_time_permissions: "onPermissions",
  link_message: "onLinkMessage",
  dataserver: "onDataserver",
  http_response: "onHttpResponse",
  moving_start: "onMovingStart",
  moving_end: "onMovingEnd",
  at_target: "onAtTarget",
  not_at_target: "onNotAtTarget",
  at_rot_target: "onAtRotTarget",
};

/** Events that can use llDetected* functions */
export const DETECTED_EVENTS = new Set([
  "touch_start", "touch", "touch_end",
  "collision_start", "collision", "collision_end",
  "sensor",
]);

/** LSL event parameter signatures (for completion snippets and hover) */
export const EVENT_PARAMS: Record<string, string> = {
  state_entry: "()",
  state_exit: "()",
  touch_start: "(integer num_detected)",
  touch: "(integer num_detected)",
  touch_end: "(integer num_detected)",
  timer: "()",
  listen: "(integer channel, string name, key id, string message)",
  link_message: "(integer sender_num, integer num, string str, key id)",
  collision_start: "(integer num_detected)",
  collision: "(integer num_detected)",
  collision_end: "(integer num_detected)",
  sensor: "(integer num_detected)",
  no_sensor: "()",
  on_rez: "(integer start_param)",
  changed: "(integer change)",
  run_time_permissions: "(integer perm)",
  money: "(key id, integer amount)",
  attach: "(key id)",
  control: "(key id, integer level, integer edge)",
  dataserver: "(key queryid, string data)",
  http_response: "(key request_id, integer status, list metadata, string body)",
  http_request: "(key id, string method, string body)",
  at_target: "(integer tnum, vector targetpos, vector ourpos)",
  not_at_target: "()",
  at_rot_target: "(integer tnum, rotation targetrot, rotation ourrot)",
  not_at_rot_target: "()",
  moving_start: "()",
  moving_end: "()",
  land_collision_start: "(vector pos)",
  land_collision: "(vector pos)",
  land_collision_end: "(vector pos)",
  email: "(string time, string address, string subj, string message, integer num_left)",
  remote_data: "(integer event_type, key channel, key message_id, string sender, integer idata, string sdata)",
  object_rez: "(key id)",
  experience_permissions: "(key agent_id)",
  experience_permissions_denied: "(key agent_id, integer reason)",
  path_update: "(integer type, list reserved)",
  transaction_result: "(key id, integer success, string data)",
};
